//This creates a hover function when moving around the image with the mouse//
$(document).ready(function(){
    $("#work1").mouseover(function(){
      $("#black1").show();
    }).mouseout(function(){
      $("#black1").hide();
    });
  });
  $(document).ready(function(){
    $("#work2").mouseover(function(){
      $("#ontario").show();
    }).mouseout(function(){
      $("#ontario").hide();
    });
  });
  $(document).ready(function(){
    $("#work3").mouseover(function(){
      $("#brown").show();
    }).mouseout(function(){
      $("#brown").hide();
    });
  })
  $(document).ready(function(){
    $("#work4").mouseover(function(){
      $("#black2").show();
    }).mouseout(function(){
      $("#black2").hide();
    });
  })
  $(document).ready(function(){
    $("#work5").mouseover(function(){
      $("#black5").show();
    }).mouseout(function(){
      $("#black5").hide();
    });
  })
  $(document).ready(function(){
    $("#work6").mouseover(function(){
      $("#black6").show();
    }).mouseout(function(){
      $("#black6").hide();
    });
  })
  $(document).ready(function(){
    $("#work7").mouseover(function(){
      $("#black7").show();
    }).mouseout(function(){
      $("#black7").hide();
    });
  })
  $(document).ready(function(){
    $("#work8").mouseover(function(){
      $("#black8").show();
    }).mouseout(function(){
      $("#black8").hide();
    });
  })